name: main
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Gradle clean
        run: |
          ./gradlew clean
      - name: Gradle build
        run: |
          ./gradlew build
      - name: Gradle publish to mavenLocal
        run: |
          ./gradlew publishToMavenLocal
      - name: Run basic example
        run: |
          cd examples/basic
          ./gradlew clean --refresh-dependencies
      - name: Run change file example
        run: |
          cd examples/change_file
          ./gradlew clean --refresh-dependencies
          echo 'dotenv.filename=.env.staging' > gradle.properties
          ./gradlew clean
      - name: Run change template file example
        run: |
          cd examples/change_template_file
          ./gradlew clean --refresh-dependencies
      - name: Run hierarchical definitions example
        run: |
          cd examples/hierarchical_definitions
          ./gradlew clean --refresh-dependencies
      - name: Upload build report
        uses: actions/upload-artifact@v4
        with:
          name: build_reports
          path: plugin/build/reports
